project: 
  type: website
  output-dir: docs
  resources: 
    - .nojekyll

      
website:
  title: "Rachel Heyard"
  sidebar:
    style: "docked"
    search: true
    background: "#8ac1c9"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - teaching.qmd
      - talks.qmd

format:
  html:
    # theme: yeti
    css: styles.scss
    toc: true


# editor: visual

