project: 
  type: website

      
website:
  title: "Rachel Heyard"
  sidebar:
    style: "docked"
    search: true
    background: "#8ac1c9"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: "**Research Outputs**"
        contents:
          - publications.qmd
          - talks.qmd
          - software.qmd
      - section: "**......**"
        contents:
          - other.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

