project: 
  type: website
  output-dir: docs

      
website:
  title: "Rachel Heyard"
  sidebar:
    style: "docked"
    search: true
    background: "#8ac1c9"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: "**Projects**"
        contents: 
          - projects/projects.qmd
          # - projects/outreach.qmd
      - section: "**Research Outputs**"
        contents:
          - publications.qmd
          - talks.qmd
          - software.qmd
      - other.qmd

format:
  html:
    # theme: yeti
    css: styles.scss
    toc: true


# editor: visual

