---
title: "Talks"
---

| Date       | Event | Location  | Title | Slides |
|------------|---------------|------------|-----------------------|----------------|
| 24.06.2025 | Invited Lecture - Webinar for Statisticians in the Pharmaceutical Industry (preclinical SIG) | online | Methodology and first results of the iRISE consortium | [osf.io/a96we](https://osf.io/a96we) | 
| 31.03.2025 | Invited Lecture - Seminar in Psychometrics | Prague (CZ) | Methodological innovations in decision‑making for research funding with a focus on transparency and reproducibility" | [osf.io/5kdyp](https://osf.io/5kdyp) | 
| 5.02.2025 | Keynote at PhD Satellite Event  | Basel (CH) | Plan well! Transparent and reproducible research practices for clinical research | [osf.io/4cvfw](https://osf.io/4cvfw) | 
| 28.11.2024 | Invited Lecture - CRESS | Paris (FR) | Investigating differences between results from RCTs and their non‑randomised emulations | [osf.io/8cekj](https://osf.io/8cekj) | 
| 29.10.2024 | META-REP conference 2024 | Munich (DE)| The iRISE Theory Work Package: Methodology and First Results | [osf.io/5sabg](https://osf.io/5sabg) | 
| 23.09.2024 | Lunch&Learn Open Science, UZH |  online | FAIR data for reproducible research | [osf.io/bqwk9](https://osf.io/bqwk9) | 
| 12.09.2024 | METRICS International Forum | online | Explaining shrinkage and heterogeneity in large‑scale replication projects using meta‑regressions | [osf.io/2xhr6](https://osf.io/2xhr6) | 
| 02.05.2024 | Invited Lecture | Swedish Research Council, Stockholm (Sweden) | Uncertainty in research funding allocation | [osf.io/uvw4a](https://osf.io/uvw4a) | 
| 23.11.2023 | Workshop “Having the bird’s eye view: Introduction to metascientific research practices” | University of Zurich (CH) | The limits and biases of published literature - From questionable research practices to publication bias | [osf.io/5uqzs](https://osf.io/5uqzs) | 
| 25.10.2023 | Open Access and The Revolution in Academic Publishing (Input lecture and panelist) | [online (CH)](https://eu.airmeet.com/e/da148190-5212-11ee-9890-296dead2c55d) | There is more to research than just papers - Alternative Research Outputs in Switzerland | [osf.io/mbzrd](https://osf.io/mbzrd) | 
| 11.09.2023 | Open and Reproducible Practices for Experimental Research Summer School | EPFL, Lausanne (CH) | Keep calm and plan well | [osf.io/c5mne](https://osf.io/c5mne) | 
| 08.03.2023 | IfB Doctoral Colloquium  | ETH Zurich (CH) | Simple Rules for Good Research Practice | [osf.io/jzv5p](https://osf.io/jzv5p) | 
| 08.02.2023 | Keynote at Peer Review under Review, ESO Workshop | Garching bei München (DE) | Let's talk about uncertainty in funding allocation | [osf.io/3r7et](https://osf.io/3r7et) | 
| 07.10.2022 | BioMed PhD Day                                                   | Lugano (CH)    | Simple Rules for Good Research Practice | [osf.io/3dyr9](https://osf.io/3dyr9) |
| 21.09.2022 | UniNE CUSO open science workshop                                 | Neuchatel (CH) | Best practices in statistical design and reporting | [osf.io/aqj7r](https://osf.io/aqj7r) |
| 09.09.2022 | International Congress on Peer Review and Scientific Publication | Chicago (US)   | [A Bayesian Approach to Reduce Bias in the Ranking of Peer-Reviewed Grant Proposals Submitted to the Swiss National Science Foundation](https://peerreviewcongress.org/abstract/a-bayesian-approach-to-reduce-bias-in-the-ranking-of-peer-reviewed-grant-proposals-submitted-to-the-swiss-national-science-foundation#video) | [rachelhey.github.io/talks/BR_chicago](https://rachelhey.github.io/talks/BR_chicago/#1) |
| 06.04.2022 | Lunch and Learn Open Science | Online | Open and FAIR Data | [www.ub.uzh.ch/...](https://www.ub.uzh.ch/dam/jcr:36b24a3a-04e2-45c3-a055-cc79339608cd/220406_Lunch+Learn_RachelHeyard.pdf) |
| 29.09.2021 | Meeting of the UNECE Group of Experts on Gender Statistics 2021 | Online | Communicating the effect of gender in research funding, during lockdown and beyond | [unece.org/...](https://unece.org/sites/default/files/2021-09/PPP_heyard_switzerland_eng.pdf)
