name: Quarto Publish

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add .nojekyll
        run: touch docs/.nojekyll
        
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          # If you use R/Python, install relevant packages here

      - name: Render site
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages  
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

